
-- CRIAR A TABELA
CREATE TABLE TB_CONTATOS_AGENDA (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100),
    telefone VARCHAR(100),
    email VARCHAR(100),
    data_nascimento DATE
);


-- INSERINDO INFORMAÇÕES NA BASE DE DADOS
INSERT INTO TB_CONTATOS_AGENDA (nome, telefone, email, data_nascimento)
VALUES('Karen', '(17) 93132-3512', 'karen@gmail.com', '1994-05-24'),
	  ('Márcio', '(15) 35932-8367', 'marcio@gmail.com', '1990-03-29'),
      ('Henrique', '(21) 31728-9482', 'henrique@gmail.com', '1985-10-12'),
      ('Gustavo', '(14) 12154-3287', 'gustavo@gmail.com', '1999-02-03');
      
-- CONSULTA INICIAL DOS DADOS
SELECT * FROM TB_CONTATOS_AGENDA;


-- INCLUIR UMA NOVA COLUNA NA TABELA DE CONTATOS
-- "COLUMN" é opcional
ALTER TABLE TB_CONTATOS_AGENDA
ADD COLUMN ativo BOOLEAN DEFAULT TRUE;

ALTER TABLE TB_CONTATOS_AGENDA 
ADD cidade VARCHAR(50);


-- ALTERANDO O TIPO DE DADO DE UMA COLUNA
ALTER TABLE TB_CONTATOS_AGENDA
MODIFY COLUMN nome VARCHAR(150) NOT NULL;


-- MUDAR NA APRESENTAÇÃO
SELECT id, nome, telefone as celular FROM TB_CONTATOS_AGENDA;


-- ALTERAR O NOME DE UMA COLUNA NA TABELA CONTATOS
ALTER TABLE TB_CONTATOS_AGENDA
CHANGE COLUMN telefone celular VARCHAR(20);

-- ALTER PARA ELIMINAR UMA COLUNA
-- DA ESTRUTURA DA TABELA
ALTER TABLE TB_CONTATOS_AGENDA
DROP COLUMN ativo;