

-- ACESSANDO O BANCO DE DADOS
USE nome_banco_de_dados;


-- CRIANDO A TABELA CONTA
CREATE TABLE TB_CONTA (
	id_cliente INT PRIMARY KEY,
    nome_cliente VARCHAR(100) NOT NULL,
    saldo DECIMAL(10,2) NOT NULL
);


-- INSERINDO REGISTROS NA TABELA DE CONTAS
INSERT INTO TB_CONTA (id_cliente, nome_cliente, saldo)
VALUES (1, 'Ana', '1000.00'),
	   (2, 'Luiz', '700.00');
       
       
-- CONSULTA INICIAL DA TABELA CONTA
SELECT * FROM TB_CONTA;




-- EXEMPLO 1 - COMANDO 'COMMIT', SALVANDO AS ALTERAÇÕES
-- AJUSTANDO O SALDO DO CLIENTE LUIZ

-- INICIANDO A TRANSAÇÃO 
START TRANSACTION;

-- AJUSTE DO SALDO DO LUIZ
UPDATE TB_CONTA
SET saldo = saldo + 250.00
WHERE id_cliente = 2;

-- SALVANDO A MODIFICAÇÃO - COMANDO 'COMMMIT'
COMMIT;




-- EXEMPLO 2 - COMANDO 'ROLLBACK', DESFAZENDO AS MODIFICAÇÕES
-- AJUSTANDO O SALDO DA CLIENTE ANA

-- INICIANDO A TRANSAÇÃO 
START TRANSACTION;

-- AJUSTE DO SALDO DA ANA
UPDATE TB_CONTA
SET saldo = saldo + 300.00
WHERE id_cliente = 1;

-- DESFAZENDO A TRANSAÇÃO
ROLLBACK;





-- EXEMPLO 3 - COMANOD 'SAVEPOINT'
-- CRIANDO PONTOS DE SALVAMENTO DURANTE A TRANSAÇÃO

-- INICIANDO A TRANSAÇÃO 
START TRANSACTION;

-- TRANSFERÊNCIA PARA O LUIZ
UPDATE TB_CONTA
SET saldo = saldo + 550
WHERE id_cliente = 2;

-- CRIANDO UM PONTO DE SALVAMENTO
SAVEPOINT PONTO_SAVE_01;

-- TRANSFERÊNCIA PARA A ANA
UPDATE TB_CONTA
SET saldo = saldo + 150.00
WHERE id_cliente = 1;

-- DESFAZENDO A TRANSFERÊNCIA PARA A ANA
ROLLBACK TO SAVEPOINT PONTO_SAVE_01;

-- DESFAZENDO A TRANSFERÊNCIA PARA O LUIZ
ROLLBACK;



-- VERIFICANDO O RESULTADO DA TABELA APÓS A TRANSAÇÃO
SELECT * FROM TB_CONTA;
