
-- EXEMPLOS COMANDOS DML
-- CRIANDO A TABELA DE EXEMPLO
CREATE TABLE TB_CLIENTE_BANCO (
	id_cliente INT AUTO_INCREMENT PRIMARY KEY,
	nome_cliente VARCHAR(120) NOT NULL,
	saldo_bancario DECIMAL(10,2),
	email VARCHAR(100)
);

-- INSERINDO REGISTROS
INSERT INTO TB_CLIENTE_BANCO (nome_cliente, saldo_bancario, email)
VALUES(),
	  (),
	  (),
	  ();
      
      
-- CONSULTANDO OS REGISTROS
SELECT * FROM TB_CLIENTE_BANCO;

-- ALTERAR/ATUALIZAR
UPDATE TB_CLIENTE_BANCO
SET email = 'cezar@email.com.br'
WHERE id_cliente = 1;

-- CORREÇÃO DOS DEMAIS PEDIDOS
UPDATE TB_CLIENTES_BANCO
SET email = concat(email, 'br')
WHERE id_cliente != 1;

-- DELETANDO REGISTROS
DELETE FROM TB_CLIENTE_BANCO
WHERE id_cliente = 4;

-- EXEMPLO DE TRANSAÇÕES EM BANCO DE DADOS
START TRANSACTION;

UPDATE TB_CLIENTE_BANCO
SET saldo_bancario = saldo_bancario + 500
WHERE id_cliente = 1;

-- DESFAZER TRANSAÇÃO
ROLLBACK;
-- ACEITAR TRANSAÇÃO
COMMIT;